pcl: upgrade to 1.10.1 and keep 1.9.1 for ROS1
* this allows us to drop PARALLEL_MAKE restriction at least for ROS2
  distributions
* recipes in current melodic aren't compatible with 1.10 and newer pcl,
  e.g. following recipes are failing:
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/robosense/rslidar-driver_1.0.2.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/cartographer-ros/cartographer-ros_1.0.0-1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ar-track-alvar/ar-track-alvar_0.7.1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ainstein-radar/ainstein-radar-filters_2.0.2-1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/sick-scan/sick-scan_1.4.2-1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ibeo-lux/ibeo-lux_2.0.1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/grid-map/grid-map-pcl_1.6.2-1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/mcl-3dl/mcl-3dl_0.2.1-1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/jsk-common/image-view2_2.2.10.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/robot-self-filter/robot-self-filter_0.1.31.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/grid-map/grid-map-sdf_1.6.2-1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/neonavigation/safety-limiter_0.8.1-1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/ouster/ouster-driver_0.1.7.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/neonavigation/map-organizer_0.8.1-1.bb:do_compile
  ros1-melodic-gatesgarth/meta-ros/meta-ros1-melodic/generated-recipes/multi-object-tracking-lidar/multi-object-tracking-lidar_1.0.2-1.bb:do_compile

  with errors like:

$ grep error: log.world.pcl-1.10 | sed 's/^.*:.*:.*: error:/error:/g' | sort | uniq -c | sort -n
      3 error: no match for call to '(pcl::detail::CopyPointHelper<mcl_3dl::PointXYZIL, mcl_3dl::PointXYZIL, void>) (const mcl_3dl::PointXYZIL&, mcl_3dl::PointXYZIL&)'
      3 error: no match for call to '(pcl::detail::CopyPointHelper<pcl::PointXYZ, mcl_3dl::PointXYZIL, void>) (const pcl::PointXYZ&, mcl_3dl::PointXYZIL&)'
      3 error: no match for call to '(pcl::detail::CopyPointHelper<pcl::PointXYZ, pcl::PointXYZ, void>) (const pcl::PointXYZ&, pcl::PointXYZ&)'
      3 error: no match for call to '(pcl::detail::CopyPointHelper<pcl::PointXYZI, mcl_3dl::PointXYZIL, void>) (const pcl::PointXYZI&, mcl_3dl::PointXYZIL&)'
      3 error: no match for call to '(pcl::getFieldIndex<mcl_3dl::PointXYZIL>::<lambda(const int&)>) (const pcl::PCLPointField&)'
      3 error: no match for call to '(pcl::getFieldIndex<pcl::PointXYZ>::<lambda(const int&)>) (const pcl::PCLPointField&)'
      6 error: no match for call to '(pcl::detail::CopyPointHelper<pcl::PointXYZRGB, pcl::PointXYZRGB, void>) (const pcl::PointXYZRGB&, pcl::PointXYZRGB&)'
     12 error: 'type' is not a member of 'pcl::traits::datatype<PointRadarTarget, pcl::fields::azimuth>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<PointRadarTarget, pcl::fields::elevation>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<PointRadarTarget, pcl::fields::range>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<PointRadarTarget, pcl::fields::snr>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<PointRadarTarget, pcl::fields::speed>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<PointRadarTarget, pcl::fields::x>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<PointRadarTarget, pcl::fields::y>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<PointRadarTarget, pcl::fields::z>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointOS1, pcl::fields::intensity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointOS1, pcl::fields::reflectivity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointOS1, pcl::fields::ring>::decomposed' {aka 'pcl::traits::decomposeArray<unsigned char>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointOS1, pcl::fields::t>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointOS1, pcl::fields::x>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointOS1, pcl::fields::y>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointOS1, pcl::fields::z>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIF, pcl::fields::intensity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIF, pcl::fields::reflectivity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIF, pcl::fields::x>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIF, pcl::fields::y>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIF, pcl::fields::z>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIFN, pcl::fields::intensity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIFN, pcl::fields::noise>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIFN, pcl::fields::reflectivity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIFN, pcl::fields::x>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIFN, pcl::fields::y>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIFN, pcl::fields::z>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIR, pcl::fields::intensity>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIR, pcl::fields::ring>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIR, pcl::fields::x>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIR, pcl::fields::y>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIR, pcl::fields::z>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRF, pcl::fields::intensity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRF, pcl::fields::reflectivity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRF, pcl::fields::ring>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRF, pcl::fields::x>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRF, pcl::fields::y>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRF, pcl::fields::z>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRFN, pcl::fields::intensity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRFN, pcl::fields::noise>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRFN, pcl::fields::reflectivity>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRFN, pcl::fields::ring>::decomposed' {aka 'pcl::traits::decomposeArray<short unsigned int>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRFN, pcl::fields::x>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRFN, pcl::fields::y>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     12 error: 'type' is not a member of 'pcl::traits::datatype<ouster_driver::OS1::PointXYZIRFN, pcl::fields::z>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     21 error: 'type' was not declared in this scope; did you mean 'boost::type'?
     24 error: 'type' is not a member of 'pcl::traits::datatype<mcl_3dl::PointXYZIL, pcl::fields::intensity>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     24 error: 'type' is not a member of 'pcl::traits::datatype<mcl_3dl::PointXYZIL, pcl::fields::label>::decomposed' {aka 'pcl::traits::decomposeArray<unsigned int>'}
     24 error: 'type' is not a member of 'pcl::traits::datatype<mcl_3dl::PointXYZIL, pcl::fields::x>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     24 error: 'type' is not a member of 'pcl::traits::datatype<mcl_3dl::PointXYZIL, pcl::fields::y>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     24 error: 'type' is not a member of 'pcl::traits::datatype<mcl_3dl::PointXYZIL, pcl::fields::z>::decomposed' {aka 'pcl::traits::decomposeArray<float>'}
     39 error: 'make_shared' is not a member of 'pcl'
     39 error: expected primary-expression before ')' token
     39 error: expected primary-expression before '>' token
    129 error: 'type' was not declared in this scope
    144 error: no match for call to '(pcl::getFieldIndex(const pcl::PCLPointCloud2&, const string&)::<lambda(int)>) (const pcl::PCLPointField&)'
    144 error: no match for call to '(pcl::getFieldsList(const pcl::PCLPointCloud2&)::<lambda(const int&, const int&)>) (std::__cxx11::basic_string<char>&, const pcl::PCLPointField&)'
    144 error: request for member 'indices' in 'index', which is of non-class type 'const int'
    147 error: no match for call to '(pcl::PolygonMesh::concatenate(pcl::PolygonMesh&, const pcl::PolygonMesh&)::<lambda(int)>) (const pcl::Vertices&)'
    150 error: 'pcl::traits::HasNoNormal' has not been declared
    150 error: 'pcl::traits::HasNoXY' has not been declared
    150 error: 'pcl::traits::HasNoXYZ' has not been declared
    150 error: 'pcl::traits::HasNormal' has not been declared
    150 error: 'pcl::traits::HasXY' has not been declared
    150 error: 'pcl::traits::HasXYZ' has not been declared
    150 error: 'remove_all_extents_t' in namespace 'std' does not name a template type; did you mean 'remove_all_extents'?
    150 error: no match for call to '(pcl::toPCLPointCloud2(const pcl::PCLPointCloud2&, pcl::PCLImage&)::<lambda(const int&)>) (const pcl::PCLPointField&)'
    150 error: redefinition of 'template<class PointT, <typeprefixerror><anonymous> > bool pcl::isNormalFinite(const PointT&)'
    150 error: redefinition of 'template<class PointT, <typeprefixerror><anonymous> > bool pcl::isXYFinite(const PointT&)'
    150 error: redefinition of 'template<class PointT, <typeprefixerror><anonymous> > bool pcl::isXYZFinite(const PointT&)'
    270 error: the value of 'NrDims' is not usable in a constant expression
    288 error: expected initializer before '<' token
    300 error: #error PCL requires C++14 or above
    300 error: 'type' is not a member of 'pcl::traits::datatype<pcl::BRISKSignature512, pcl::fields::brisk_descriptor512>::decomposed' {aka 'pcl::traits::decomposeArray<unsigned char [64]>'}
....
    300 error: 'type' is not a member of 'pcl::traits::datatype<pcl::_ReferenceFrame, pcl::fields::z_axis>::decomposed' {aka 'pcl::traits::decomposeArray<float [3]>'}
    432 error: expected unqualified-id before '>' token
    432 error: type/value mismatch at argument 3 in template parameter list for 'template<class PointInT, class PointOutT, class Enable> struct pcl::detail::CopyPointHelper'
    441 error: request for member 'vertices' in 'polygon', which is of non-class type 'int'
    582 error: request for member 'name' in 'field', which is of non-class type 'const int'
    864 error: 'enable_if_t' is not a member of 'std'
    900 error: expected '>' before '<' token
   1458 error: use of 'auto' in lambda parameter declaration only available with '-std=c++14' or '-std=gnu++14'
   4776 error: 'enable_if_t' in namespace 'std' does not name a template type
  26574 error: 'divscalar' is not a member of 'pcl::traits'
  26574 error: 'minus' is not a member of 'pcl::traits'
  26574 error: 'minusscalar' is not a member of 'pcl::traits'
  26574 error: 'mulscalar' is not a member of 'pcl::traits'
  26574 error: 'plus' is not a member of 'pcl::traits'
  26574 error: 'plusscalar' is not a member of 'pcl::traits'
  26574 error: template argument 1 is invalid

Signed-off-by: Martin Jansa <martin.jansa@lge.com>